# Generated by Django 5.0.2 on 2024-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='postpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('data_rollover', models.IntegerField(default=0)),
                ('sms_per_day', models.CharField(max_length=500)),
                ('entertainment_apps', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
