# Generated by Django 5.0.2 on 2024-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_postpaid_sms_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaid',
            name='calls',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='postpaid',
            name='sms_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
