# Generated by Django 5.0.2 on 2024-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_postpaid_calls_postpaid_sms_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaid',
            name='data_rollover',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='sms_per_day',
            field=models.CharField(max_length=50),
        ),
    ]
