# Generated by Django 5.0.2 on 2024-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaid',
            name='validity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
