# Generated by Django 5.0.2 on 2024-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_prepaid_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='dth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dth_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('channels', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
