# Generated by Django 5.0.2 on 2024-06-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_postpaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpaid',
            name='sms_per_day',
        ),
    ]
