# Generated by Django 5.0.2 on 2024-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_dth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dth',
            name='validity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
