# Generated by Django 5.1.2 on 2025-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_dth_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('sub_category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
